### ISSUE TITLE
Remove code-level consistency check in Innovatrics Document Provider

### ISSUE THREAD

**Issue by jnpsk** [wultra/enrollment-server#960]
For example Czech Identity Card has ČESKÁ REPUBLIKA in the Nationality field in visual zone, but CZE in machine readable zone. That creates false alarm in text consistency check of Innovatrics document verification. To overcome this issue https://github.com/wultra/enrollment-server/issues/907 implemented postprocessing of the text consistency check. However this should be managed on Innovatrics instance configuration level. The example bellow excludes `documentNumber` filed from consistency check of SVK identity card 2022 edition.

```yml
innovatrics:
  dot:
    dis:
      customer:
        document:
          inspection:
            text-consistency-check:
              SVK_identity-card_2022-12-01:
                exclusions:
                  - documentNumber
```
